name: OpenAPI Docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install redoc-cli
        run: yarn global add redoc-cli
      - name: Build Docs
        run: redoc-cli build openapi.yaml -o dist/index.html
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
