name: OpenAPI Docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Docs
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'build openapi.yaml -o dist/index.html'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/
